"""Model Games added

Revision ID: 098118c1aaca
Revises: 4387c3efe638
Create Date: 2025-12-24 13:22:25.614987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098118c1aaca'
down_revision: Union[str, Sequence[str], None] = '4387c3efe638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dm_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='game_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dm_user_id'], ['users.id'], name=op.f('fk_games_dm_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_dm_user_id'), 'games', ['dm_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_dm_user_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
