"""create_game_notes_table

Revision ID: 8fc504d109a5
Revises: 20260125130000
Create Date: 2026-01-28 12:37:01.414532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc504d109a5'
down_revision: Union[str, Sequence[str], None] = '20260125130000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'game_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('visibility', sa.Enum('PRIVATE', 'SHARED', name='notevisibility'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_notes_game_id_games'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_notes_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_game_notes'))
    )
    op.create_index(op.f('ix_game_notes_game_id'), 'game_notes', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_notes_user_id'), 'game_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_notes_user_id'), table_name='game_notes')
    op.drop_index(op.f('ix_game_notes_game_id'), table_name='game_notes')
    op.drop_table('game_notes')
    sa.Enum(name='notevisibility').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
