"""Rename token to token_hash for security

Revision ID: e949c52db9e4
Revises: be3a5445f0b2
Create Date: 2025-12-20 17:21:07.909438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e949c52db9e4'
down_revision: Union[str, Sequence[str], None] = 'be3a5445f0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column from 'token' to 'token_hash'
    op.alter_column('auth_refresh_tokens', 'token',
                    new_column_name='token_hash',
                    existing_type=sa.String(length=255),
                    type_=sa.String(length=64),
                    existing_nullable=False)
    
    # Drop old index and create new one with updated name
    op.drop_index(op.f('ix_auth_refresh_tokens_token'), table_name='auth_refresh_tokens')
    op.create_index(op.f('ix_auth_refresh_tokens_token_hash'), 'auth_refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse: rename column from 'token_hash' back to 'token'
    op.alter_column('auth_refresh_tokens', 'token_hash',
                    new_column_name='token',
                    existing_type=sa.String(length=64),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    
    # Drop new index and recreate old one
    op.drop_index(op.f('ix_auth_refresh_tokens_token_hash'), table_name='auth_refresh_tokens')
    op.create_index(op.f('ix_auth_refresh_tokens_token'), 'auth_refresh_tokens', ['token'], unique=True)
    # ### end Alembic commands ###
